networks:
  finance-manager-network:
    driver: bridge

services:
  pg-0:
    image: bitnami/postgresql-repmgr:17
    container_name: pg-0
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
      - ./pkg/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD:-postgres}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-postgres}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-postgres}
      - POSTGRESQL_DATABASE=finance_manager
      - REPMGR_PASSWORD=${REPMGR_PASSWORD:-postgres}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    networks:
      - finance-manager-network

  pg-1:
    image: bitnami/postgresql-repmgr:17
    container_name: pg-1
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD:-postgres}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-postgres}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-postgres}
      - POSTGRESQL_DATABASE=finance_manager
      - REPMGR_PASSWORD=${REPMGR_PASSWORD:-postgres}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    networks:
      - finance-manager-network

  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER:-postgres}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD:-postgres}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME:-postgres}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD:-postgres}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME:-postgres}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - finance-manager-network

  finance-manager:
    image: finance-manager:latest
    container_name: finance-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - pgpool
    environment:
      - PG_URL=${PG_URL}
    networks:
      - finance-manager-network

volumes:
  pg_0_data:
  pg_1_data:
